export { default as DashboardPage } from './DashboardPage';
export { default as UsersManagement } from './UsersManagement';
export { default as ShopsManagement } from './ShopsManagement';
export { default as ServicesManagement } from './ServicesManagement';
export { default as ReportsPage } from './ReportsPage';
export { default as SystemSettings } from './SystemSettings';
export { default as AccountsManagement } from './AccountsManagement';
export { default as HotelsManagement } from './HotelsManagement';
export { default as AppointmentsManagement } from './AppointmentsManagement'; 